#ifndef  _DEFINITIONS_H_
#define  _DEFINITIONS_H_

#define ROADSPEED 6
#define BACKGROUNDSPEED 4
#define SCORE_FONT_SIZE 0.1
#define TRANSITION_TIME 1
#define MAN_WIDTH 0.15	
#define MAN_HEIGHT 0.3	
#define MAN_COLLISION_BITMASK 1

#endif //_DEFINITIONS_H_